using ThemeManager.Core.Skins;

namespace ThemeManager.Tests;

/// <summary>
/// Tests for <see cref="SkinDefinition"/>, <see cref="MeasureDefinition"/>,
/// <see cref="MeterDefinition"/>, and <see cref="SkinDefaults"/>.
/// </summary>
public class SkinModelTests
{
    // ── SkinDefinition defaults ──────────────────────────────────────────────

    [Fact]
    public void SkinDefinition_HasSaneDefaults()
    {
        var skin = new SkinDefinition();
        Assert.Equal("New Widget", skin.Name);
        Assert.True(skin.Enabled);
        Assert.Equal(0.90, skin.Opacity);
        Assert.False(skin.ClickThrough);
        Assert.False(skin.Locked);
        Assert.NotEmpty(skin.Id);
        Assert.Equal(220, skin.Width);
        Assert.Equal(120, skin.Height);
    }

    [Fact]
    public void SkinDefinition_OpacityRange()
    {
        var skin = new SkinDefinition();
        Assert.InRange(skin.Opacity, 0.0, 1.0);
    }

    // ── MeasureDefinition ────────────────────────────────────────────────────

    [Fact]
    public void MeasureDefinition_DefaultName_IsEmpty()
    {
        var measure = new MeasureDefinition();
        Assert.Equal("", measure.Name);
        Assert.Equal(MeasureType.Cpu, measure.Type); // First enum value
    }

    [Theory]
    [InlineData(MeasureType.Cpu)]
    [InlineData(MeasureType.Memory)]
    [InlineData(MeasureType.DiskFree)]
    [InlineData(MeasureType.DiskUsed)]
    [InlineData(MeasureType.Time)]
    [InlineData(MeasureType.Date)]
    [InlineData(MeasureType.Uptime)]
    [InlineData(MeasureType.NetworkDown)]
    [InlineData(MeasureType.NetworkUp)]
    [InlineData(MeasureType.Battery)]
    public void MeasureType_AllValues_AreValid(MeasureType type)
    {
        var measure = new MeasureDefinition { Type = type };
        Assert.Equal(type, measure.Type);
    }

    // ── MeterDefinition ──────────────────────────────────────────────────────

    [Fact]
    public void MeterDefinition_HasSaneDefaults()
    {
        var meter = new MeterDefinition();
        Assert.Equal(MeterKind.String, meter.Kind);
        Assert.Equal(140, meter.Width);
        Assert.Equal(22, meter.Height);
        Assert.Equal(13, meter.FontSize);
        Assert.False(meter.Bold);
        Assert.Equal(100, meter.BarMax);
        Assert.Equal("{0:F0}", meter.Format);
    }

    [Fact]
    public void MeterDefinition_Id_IsAutoGenerated()
    {
        var m1 = new MeterDefinition();
        var m2 = new MeterDefinition();
        Assert.NotEqual(m1.Id, m2.Id);
    }

    [Fact]
    public void MeterDefinition_IconKind_DefaultsToEmptyGlyph()
    {
        var meter = new MeterDefinition { Kind = MeterKind.Icon };
        Assert.Equal(MeterKind.Icon, meter.Kind);
        Assert.Equal("", meter.IconGlyph); // IconMeterViewModel falls back to a generic glyph at render time
    }

    // ── SkinDefaults (built-in widgets) ──────────────────────────────────────

    [Fact]
    public void CreateClock_HasTimeAndDateMeasures()
    {
        var clock = SkinDefaults.CreateClock();
        Assert.Equal("Cozy Clock", clock.Name);
        Assert.Equal("builtin-clock", clock.Id);
        Assert.Equal(2, clock.Measures.Count);
        Assert.Contains(clock.Measures, m => m.Type == MeasureType.Time);
        Assert.Contains(clock.Measures, m => m.Type == MeasureType.Date);
        Assert.Equal(2, clock.Meters.Count);
    }

    [Fact]
    public void CreateSystemMonitor_HasCpuMemDisk()
    {
        var monitor = SkinDefaults.CreateSystemMonitor();
        Assert.Equal("System Monitor", monitor.Name);
        Assert.Equal(3, monitor.Measures.Count);
        Assert.Contains(monitor.Measures, m => m.Type == MeasureType.Cpu);
        Assert.Contains(monitor.Measures, m => m.Type == MeasureType.Memory);
        Assert.Contains(monitor.Measures, m => m.Type == MeasureType.DiskFree);
        // Each measure gets a label + bar = 6 meters
        Assert.Equal(6, monitor.Meters.Count);
    }

    [Fact]
    public void CreateUptime_HasUptimeMeasure()
    {
        var uptime = SkinDefaults.CreateUptime();
        Assert.Equal("Uptime", uptime.Name);
        Assert.Single(uptime.Measures);
        Assert.Equal(MeasureType.Uptime, uptime.Measures[0].Type);
    }

    [Fact]
    public void CreateAllDefaults_ReturnsFourWidgets()
    {
        var all = SkinDefaults.CreateAllDefaults();
        Assert.Equal(4, all.Count);
        Assert.All(all, s =>
        {
            Assert.NotEmpty(s.Id);
            Assert.NotEmpty(s.Name);
            Assert.NotEmpty(s.Measures);
            Assert.NotEmpty(s.Meters);
        });
    }

    [Fact]
    public void CreateAllDefaults_AllHaveUniqueIds()
    {
        var all = SkinDefaults.CreateAllDefaults();
        var ids = all.Select(s => s.Id).ToList();
        Assert.Equal(ids.Count, ids.Distinct().Count());
    }

    [Fact]
    public void CreateAllDefaults_AllEnabled()
    {
        var all = SkinDefaults.CreateAllDefaults();
        Assert.All(all, s => Assert.True(s.Enabled));
    }

    [Fact]
    public void CreateNetworkMonitor_HasNetworkMeasures()
    {
        var net = SkinDefaults.CreateAllDefaults().Find(s => s.Name == "Network");
        Assert.NotNull(net);
        Assert.Contains(net!.Measures, m => m.Type == MeasureType.NetworkDown);
        Assert.Contains(net.Measures, m => m.Type == MeasureType.NetworkUp);
    }
}
