using ThemeManager.Core.Skins;

namespace ThemeManager.Tests;

public class SkinModelTests
{
    [Fact]
    public void SkinDefinition_HasSaneDefaults()
    {
        var skin = new SkinDefinition();
        Assert.Equal("New Widget", skin.Name);
        Assert.True(skin.Enabled);
        Assert.Equal(0.90, skin.Opacity);
        Assert.False(skin.ClickThrough);
        Assert.False(skin.AlwaysOnTop);
        Assert.False(skin.Locked);
        Assert.NotEmpty(skin.Id);
        Assert.Equal(220, skin.Width);
        Assert.Equal(120, skin.Height);
        Assert.Equal(4, skin.SchemaVersion);
    }

    [Fact]
    public void SkinDefinition_OpacityRange() => Assert.InRange(new SkinDefinition().Opacity, 0.0, 1.0);

    [Fact]
    public void MeasureDefinition_DefaultName_IsEmpty()
    {
        var measure = new MeasureDefinition();
        Assert.Equal("", measure.Name);
        Assert.Equal(MeasureType.Cpu, measure.Type);
    }

    [Theory]
    [InlineData(MeasureType.Cpu)] [InlineData(MeasureType.Memory)] [InlineData(MeasureType.DiskFree)] [InlineData(MeasureType.DiskUsed)]
    [InlineData(MeasureType.Time)] [InlineData(MeasureType.Date)] [InlineData(MeasureType.Uptime)] [InlineData(MeasureType.NetworkDown)]
    [InlineData(MeasureType.NetworkUp)] [InlineData(MeasureType.Battery)]
    public void MeasureType_AllValues_AreValid(MeasureType type) => Assert.Equal(type, new MeasureDefinition { Type = type }.Type);

    [Fact]
    public void MeterDefinition_HasSaneDefaults()
    {
        var meter = new MeterDefinition();
        Assert.Equal(MeterKind.String, meter.Kind);
        Assert.Equal(140, meter.Width);
        Assert.Equal(22, meter.Height);
        Assert.Equal(13, meter.FontSize);
        Assert.False(meter.Bold);
        Assert.Equal(100, meter.BarMax);
        Assert.Equal("{0:F0}", meter.Format);
    }

    [Fact]
    public void MeterDefinition_Id_IsAutoGenerated() => Assert.NotEqual(new MeterDefinition().Id, new MeterDefinition().Id);

    [Fact]
    public void MeterDefinition_IconKind_DefaultsToEmptyGlyph()
    {
        var meter = new MeterDefinition { Kind = MeterKind.Icon };
        Assert.Equal(MeterKind.Icon, meter.Kind);
        Assert.Equal("", meter.IconGlyph);
    }

    [Fact]
    public void CreateClock_HasReadableTypography()
    {
        var clock = SkinDefaults.CreateClock();
        Assert.Equal("Cozy Clock", clock.Name);
        Assert.Equal(4, clock.SchemaVersion);
        Assert.False(clock.AlwaysOnTop);
        Assert.Equal(2, clock.Measures.Count);
        Assert.Equal(2, clock.Meters.Count);
        Assert.True(clock.Meters[0].Height >= clock.Meters[0].FontSize * 1.4);
        Assert.True(clock.Meters[1].Height >= clock.Meters[1].FontSize * 1.4);
    }

    [Fact]
    public void CreateSystemMonitor_HasCpuMemDisk()
    {
        var monitor = SkinDefaults.CreateSystemMonitor();
        Assert.Equal("System Monitor", monitor.Name);
        Assert.Equal(3, monitor.Measures.Count);
        Assert.Equal(9, monitor.Meters.Count);
        Assert.Contains(monitor.Measures, m => m.Type == MeasureType.Cpu);
        Assert.Contains(monitor.Measures, m => m.Type == MeasureType.Memory);
        Assert.Contains(monitor.Measures, m => m.Type == MeasureType.DiskFree);
    }

    [Fact]
    public void CreateUptime_HasUptimeMeasure()
    {
        var uptime = SkinDefaults.CreateUptime();
        Assert.Equal("Uptime", uptime.Name);
        Assert.Single(uptime.Measures);
        Assert.Equal(MeasureType.Uptime, uptime.Measures[0].Type);
    }

    [Fact]
    public void CreateAllDefaults_ReturnsFiveWidgets()
    {
        var all = SkinDefaults.CreateAllDefaults();
        Assert.Equal(5, all.Count);
        Assert.All(all, s => { Assert.NotEmpty(s.Id); Assert.NotEmpty(s.Name); Assert.NotEmpty(s.Measures); Assert.NotEmpty(s.Meters); });
    }

    [Fact]
    public void CreateAllDefaults_AllHaveUniqueIds()
    {
        var all = SkinDefaults.CreateAllDefaults();
        var ids = all.Select(s => s.Id).ToList();
        Assert.Equal(ids.Count, ids.Distinct().Count());
    }

    [Fact]
    public void CreateAllDefaults_AreDesktopFirst()
    {
        Assert.All(SkinDefaults.CreateAllDefaults(), s => Assert.False(s.AlwaysOnTop));
        Assert.All(SkinDefaults.CreateAllDefaults(), s => Assert.True(s.Enabled));
    }

    [Fact]
    public void CreateNetworkMonitor_HasNetworkMeasures()
    {
        var net = SkinDefaults.CreateAllDefaults().Find(s => s.Name == "Network");
        Assert.NotNull(net);
        Assert.Contains(net!.Measures, m => m.Type == MeasureType.NetworkDown);
        Assert.Contains(net.Measures, m => m.Type == MeasureType.NetworkUp);
    }

    [Fact]
    public void CreateSystemRings_HasThreeRingMeters()
    {
        var rings = SkinDefaults.CreateAllDefaults().Find(s => s.Name == "System Rings");
        Assert.NotNull(rings);
        Assert.Equal(3, rings!.Meters.Count(m => m.Kind == MeterKind.Ring));
    }

    [Fact]
    public void CreateSystemRings_UsesDiskUsedNotDiskFree()
    {
        var rings = SkinDefaults.CreateAllDefaults().Find(s => s.Name == "System Rings");
        Assert.NotNull(rings);
        Assert.DoesNotContain(rings!.Measures, m => m.Type == MeasureType.DiskFree);
        Assert.Contains(rings.Measures, m => m.Type == MeasureType.DiskUsed);
    }

    [Fact]
    public void SceneWidgetPlacement_PreservesDesktopCoordinates()
    {
        var placement = new ThemeManager.Core.Models.SceneWidgetPlacement
        {
            WidgetId = "clock",
            X = 1420,
            Y = 88,
            Scale = 1.15,
            Rotation = 4,
            Opacity = 0.72,
            ZIndex = 7,
            Visible = true,
            Monitor = "Primary"
        };

        Assert.Equal(1420, placement.X);
        Assert.Equal(88, placement.Y);
        Assert.Equal(1.15, placement.Scale);
        Assert.Equal(4, placement.Rotation);
        Assert.Equal(0.72, placement.Opacity);
        Assert.Equal(7, placement.ZIndex);
        Assert.True(placement.Visible);
        Assert.Equal("Primary", placement.Monitor);
    }

    [Fact]
    public void WebJsonPresets_ShipsAtLeastTwo() => Assert.True(WebJsonPresets.All.Count >= 2);

    [Theory]
    [MemberData(nameof(WebJsonPresetIndexes))]
    public void WebJsonPresets_EachTargetIsWellFormed(int index)
    {
        var preset = WebJsonPresets.All[index];
        Assert.False(string.IsNullOrWhiteSpace(preset.Label));
        var parts = preset.Target.Split('|', 2);
        Assert.Equal(2, parts.Length);
        Assert.True(Uri.TryCreate(parts[0], UriKind.Absolute, out var uri));
        Assert.True(uri!.Scheme is "http" or "https");
        Assert.False(string.IsNullOrWhiteSpace(parts[1]));
    }

    public static IEnumerable<object[]> WebJsonPresetIndexes() => Enumerable.Range(0, WebJsonPresets.All.Count).Select(i => new object[] { i });
}
