using System.ComponentModel;
using System.Runtime.CompilerServices;
using ThemeManager.Core.Models;

namespace ThemeManager.Core.Services;

/// <summary>
/// Central service for theme state management.
/// - Holds the active theme and raises <see cref="ThemeChanged"/> on change.
/// - Exposes an event so the WinUI layer can update its ResourceDictionary.
/// - Owns the in-memory theme list and delegates persistence to <see cref="ThemeRepository"/>.
/// </summary>
public sealed class ThemeService : INotifyPropertyChanged
{
    private readonly ThemeRepository _repo;

    // ── Observable list of all themes ──────────────────────────────────────────
    private List<CozyTheme> _themes = new();
    public IReadOnlyList<CozyTheme> Themes => _themes;

    // ── Active theme ────────────────────────────────────────────────────────────
    private CozyTheme _activeTheme = CozyDefaults.CreateDefault();
    public CozyTheme ActiveTheme
    {
        get => _activeTheme;
        private set
        {
            if (_activeTheme == value) return;
            _activeTheme = value;
            OnPropertyChanged();
            ThemeChanged?.Invoke(this, value);
        }
    }

    // ── Events ───────────────────────────────────────────────────────────────────
    /// Fired whenever the active theme changes (palette or geometry).
    public event EventHandler<CozyTheme>? ThemeChanged;
    /// Fired whenever the theme list is mutated (add/remove/rename).
    public event EventHandler? ThemeListChanged;
    public event PropertyChangedEventHandler? PropertyChanged;

    // ── Constructor ──────────────────────────────────────────────────────────────
    public ThemeService(ThemeRepository repository)
    {
        _repo = repository;
    }

    // ── Initialisation ───────────────────────────────────────────────────────────
    /// Must be called once on startup (await before showing UI).
    public async Task InitializeAsync()
    {
        _themes = await _repo.LoadAllAsync();

        var defaultTheme = _themes.Find(t => t.Id == "cozy-default")
                        ?? _themes.FirstOrDefault()
                        ?? CozyDefaults.CreateDefault();

        // Don't use the property setter here to avoid firing events before UI is ready.
        _activeTheme = defaultTheme;
    }

    // ── Active theme management ───────────────────────────────────────────────────
    /// Sets the active theme, normalizes all color fields, and fires <see cref="ThemeChanged"/>.
    public void SetActiveTheme(CozyTheme theme)
    {
        // Normalize all colors in-memory so any downstream consumer
        // (ResourceDictionary updater, system integrator, palette strip renderer)
        // always receives clean #RRGGBB values — regardless of whether the theme
        // was saved, edited via color picker, or generated by PaletteHarmonizer.
        theme.BackgroundBase = CozyTheme.NormalizeHex(theme.BackgroundBase);
        theme.BackgroundAlt  = CozyTheme.NormalizeHex(theme.BackgroundAlt);
        theme.Surface        = CozyTheme.NormalizeHex(theme.Surface);
        theme.AccentPrimary  = CozyTheme.NormalizeHex(theme.AccentPrimary);
        theme.AccentStrong   = CozyTheme.NormalizeHex(theme.AccentStrong);
        theme.TextPrimary    = CozyTheme.NormalizeHex(theme.TextPrimary);
        theme.TextMuted      = CozyTheme.NormalizeHex(theme.TextMuted);
        theme.BorderSubtle   = CozyTheme.NormalizeHex(theme.BorderSubtle);

        ActiveTheme = theme;
    }

    /// <summary>
    /// Applies a live palette token change to the active theme and fires <see cref="ThemeChanged"/>.
    /// Useful for real-time color picker updates without saving.
    /// </summary>
    public void NotifyThemeTokenChanged()
    {
        ThemeChanged?.Invoke(this, _activeTheme);
    }

    // ── CRUD ──────────────────────────────────────────────────────────────────────
    public async Task<CozyTheme> CreateThemeAsync(string name)
    {
        var theme = CozyDefaults.CreateDefault();
        theme.Id       = Guid.NewGuid().ToString();
        theme.Name     = name;
        theme.IsBuiltIn = false;
        _themes.Add(theme);
        await PersistAsync();
        ThemeListChanged?.Invoke(this, EventArgs.Empty);
        return theme;
    }

    public async Task<CozyTheme> DuplicateThemeAsync(CozyTheme source)
    {
        var clone = source.Duplicate();
        _themes.Add(clone);
        await PersistAsync();
        ThemeListChanged?.Invoke(this, EventArgs.Empty);
        return clone;
    }

    public async Task SaveThemeAsync(CozyTheme theme)
    {
        // Normalize all color fields before persisting — prevents leading-zero
        // stripping and keeps JSON consistent across all save paths.
        theme.BackgroundBase = CozyTheme.NormalizeHex(theme.BackgroundBase);
        theme.BackgroundAlt  = CozyTheme.NormalizeHex(theme.BackgroundAlt);
        theme.Surface        = CozyTheme.NormalizeHex(theme.Surface);
        theme.AccentPrimary  = CozyTheme.NormalizeHex(theme.AccentPrimary);
        theme.AccentStrong   = CozyTheme.NormalizeHex(theme.AccentStrong);
        theme.TextPrimary    = CozyTheme.NormalizeHex(theme.TextPrimary);
        theme.TextMuted      = CozyTheme.NormalizeHex(theme.TextMuted);
        theme.BorderSubtle   = CozyTheme.NormalizeHex(theme.BorderSubtle);

        theme.LastModified = DateTimeOffset.UtcNow;

        if (!_themes.Contains(theme))
            _themes.Add(theme);

        await PersistAsync();
        ThemeListChanged?.Invoke(this, EventArgs.Empty);

        // If we just saved the active theme, re-broadcast so the UI re-applies.
        if (theme.Id == _activeTheme.Id)
            ThemeChanged?.Invoke(this, theme);
    }

    public async Task DeleteThemeAsync(CozyTheme theme)
    {
        if (theme.IsBuiltIn) return; // Never delete the built-in theme.
        _themes.Remove(theme);

        // Fall back to Cozy Café if the active theme was deleted.
        if (_activeTheme.Id == theme.Id)
            SetActiveTheme(_themes.First());

        await PersistAsync();
        ThemeListChanged?.Invoke(this, EventArgs.Empty);
    }

    // ── Import / Export ───────────────────────────────────────────────────────────
    public async Task ExportThemeAsync(CozyTheme theme, string filePath)
        => await _repo.ExportThemeAsync(theme, filePath);

    public async Task<CozyTheme?> ImportThemeAsync(string filePath)
    {
        var theme = await _repo.ImportThemeAsync(filePath);
        if (theme is null) return null;
        _themes.Add(theme);
        await PersistAsync();
        ThemeListChanged?.Invoke(this, EventArgs.Empty);
        return theme;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────────
    private Task PersistAsync() => _repo.SaveAllAsync(_themes);

    private void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}
